### ISSUE TITLE
[ARCHETYPE-474] .gitignore file is not copied to archetype JAR

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-archetype#745]
**[Christian Schlichtherle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christians)** opened **[ARCHETYPE-474](https://issues.apache.org/jira/browse/ARCHETYPE-474?redirect=false)** and commented

In the file `src/main/resources/META-INF/maven/archetype-metadata.xml`, I have something like this:

```
...
<fileSets>
    <fileSet filtered="false" packaged="false">
        <directory/>
        <includes>
            <include>.*ignore</include>
        </includes>
    </fileSet>
</fileSets>
...
```

In the directory `src/main/resources/archetype-resources`, there are two files `.gitignore` and `.hgignore`. Now when I create the archetype from the resources, only the `.hgignore` file gets copied into the archetype, but not the `.gitignore` file.

---

**Affects:** 2.2, 2.3

**Comment by jira-importer** [comment]
**[Christian Schlichtherle](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=christians)** commented

I am sorry, but this issue is caused by the maven-resources-plugin:2.7, not the maven-archetype-plugin:2.3 - see http://jira.codehaus.org/browse/MRESOURCES-190 .

**Comment by mr-rycho** [comment]
* It's caused by BOTH: `maven-resources-plugin` AND `maven-archetype-plugin`
   * `maven-resources-plugin` is responsible for copying from `src/...` to `target/classes/archetype-resources`
   * `maven-archetype-plugin` is responsible for packing `target/...` to the archive
* in both cases one should use `<useDefaultExcludes>false</useDefaultExcludes>` in plugin's configuration (tested on `3.3.1` (`resources`) + `3.4.1` (`archetype`) )
